### ISSUE TITLE
Lesson1

### ISSUE THREAD

**Issue by aishize** [MariaDikhtiievska/TeyMax_Lesson1#2]
![image](https://user-images.githubusercontent.com/58956219/140908715-65f20919-8062-4435-9368-997b5f8d50f2.png)

чел, пофиксишь инпут - накину 0.5

**Comment by MariaDikhtiievska** [comment]
Мне кажется ты что-то перепутал😅. У меня нету такого инпута


вт, 9 лист. 2021 о 12:35 Eugenii ***@***.***> пише:
